package mintlin.minecraft.server.entity.metadata

import mintlin.minecraft.datastructure.*

open class LivingEntityMetadata(metadata: Metadata) : EntityMetadata(metadata)

private var livingEntityByte8 = MetadataProperty<LivingEntityMetadata, Byte>(id = 8, MetadataType.Byte) { 0 }
var LivingEntityMetadata.isHandActive by FlagDelegate(0x01, livingEntityByte8)
private var LivingEntityMetadata.isActivateMainHand by FlagDelegate(0x01, livingEntityByte8)
var LivingEntityMetadata.activeHand: Hand
    get() = if (isActivateMainHand) Hand.MainHand else Hand.OffHand
    set(value) {
        isActivateMainHand = value == Hand.MainHand
    }
var LivingEntityMetadata.isInRiptideSpinAttack by FlagDelegate(0x04, livingEntityByte8)
var LivingEntityMetadata.health by MetadataProperty(id = 9, MetadataType.Float) { 1f }
var LivingEntityMetadata.potionEffectColor by MetadataProperty(id = 10, MetadataType.VarInt) { 0 }

/**
 * reduces the number of particles generated by potions to 1/5 the normal amount
 */
var LivingEntityMetadata.isPotionEffectAmbient by MetadataProperty(id = 11, MetadataType.Boolean) { false }
var LivingEntityMetadata.numberOfArrowsInEntity by MetadataProperty(id = 12, MetadataType.VarInt) { 0 }
var LivingEntityMetadata.numberOfBeeStingersInEntity by MetadataProperty(id = 13, MetadataType.VarInt) { 0 }

//var Location of the bed that the entity is currently sleeping in
var LivingEntityMetadata.locationOfTheSleepingBed by MetadataProperty(id = 14, MetadataType.OptPosition) { }
